name: dp_pick

image_shape: [3, 256, 256]
dataset_path: outputs/collect/2025.07.26/01.31.09_Level1_pick_other_material/dataset
obs_keys: &obs_keys ['camera_1_rgb', 'camera_2_rgb', 'agent_pose']

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    camera_1_rgb:
      shape: ${task.image_shape}
      type: rgb
    camera_2_rgb:
      shape: ${task.image_shape}
      type: rgb
    agent_pose:
      shape: [8]
      type: low_dim
  action: 
    shape: [8]

dataset:
  _target_: policy.dataset.dp_image_dataset.DPImageDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  n_latency_steps: ${n_latency_steps}
  use_cache: True
  seed: 42
  val_ratio: 0.00
  max_train_episodes: null
  delta_action: False

