name: Level1_shake

task_type: "shake"
controller_type: "shake"

mode: "collect"  # "collect" or "infer"

usd_path: "assets/chemistry_lab/lab_003/lab_003.usd"
obj_path: "/World/beaker_2"
sub_obj_path: "/World/beaker_2/mesh"

max_episodes: 100

infer:
  type: "local"
  obs_names: {"camera_1_rgb": 'camera_1_rgb', "camera_2_rgb": 'camera_2_rgb'}
  policy_model_path: ""
  policy_config_path: ""
  normalizer_path: ""
  host: "127.0.0.1"
  port: 8000
  n_obs_steps: 1
  timeout: 30
  max_retries: 3

task:
  max_steps: 1000
  obj_paths:
    - path: "/World/beaker_2"
      position_range:
        x: [0.19, 0.34]
        y: [-0.075, 0.075]
        z: [0.80, 0.80]

cameras:
  - prim_path: "/World/Camera1"
    name: "camera_1"
    translation: [2, 0, 2]
    resolution: [256, 256]
    focal_length: 4
    orientation: [0.61237, 0.35355, 0.35355, 0.61237]
    image_type: "rgb"

  - prim_path: "/World/Camera2"
    name: "camera_2"
    translation: [0.1, 0, 2.5]
    resolution: [256, 256]
    focal_length: 4
    orientation: [0.70711, 0, 0, -0.70711]
    image_type: "rgb"

  - prim_path: "/World/Franka/panda_hand/arm_camera"
    name: "camera_3"
    resolution: [256, 256]
    image_type: "rgb"

robot:
  type: "franka"
  position: [-0.4, -0, 0.71]

collector:
  type: "default"
  compression: gzip  

hydra:
  run:
    dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}

multi_run:
  run_dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}
