name: Level2_openclose

task_type: "openclose"
controller_type: "openclose"

mode: "collect"
usd_path: "assets/chemistry_lab/lab_001/lab_001.usd"
handle_path: "/World/Cabinet_01/drawer_handle_top"

max_episodes: 100

infer:
  type: "local"
  obs_names: {"camera_1_rgb": 'camera_1_rgb', "camera_2_rgb": 'camera_2_rgb'}
  policy_model_path: ""
  policy_config_path: ""
  normalizer_path: ""
  host: "127.0.0.1"
  port: 8000
  n_obs_steps: 1
  timeout: 30
  max_retries: 3

task:
  max_steps: 2000
  operate_type: "drawer"
  obj_paths:
    - path: "/World/Cabinet_01"
      position_range:
        x: [0.69, 0.79]
        y: [-0.05, 0.05]
        z: [1.15, 1.15]

cameras:
  - prim_path: "/World/Camera1"
    name: "camera_1"
    translation: [-0.7, 1.4, 1.4]
    resolution: [256, 256]
    focal_length: 2
    orientation: [-0.2297, -0.18336, 0.59631, 0.74701]
    image_type: "rgb"

  - prim_path: "/World/Camera2"
    name: "camera_2"
    translation: [-1, -0.1, 3.6]
    resolution: [256, 256]
    focal_length: 4
    orientation: [0.69035, 0.15304, -0.15304, -0.69035]
    image_type: "rgb"
    
  - prim_path: "/World/Franka/panda_hand/arm_camera"
    name: "camera_3"
    resolution: [256, 256]
    image_type: "rgb"

robot:
  type: "franka"
  position: [-0.4, -0, 0.71]

collector:
  type: "default"
  compression: gzip

hydra:
  run:
    dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}

multi_run:
  run_dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}