name: Level4_OpenTransportPour

task_type: "OpenTransportPour"
controller_type: "OpenTransportPour"

mode: "collect"
usd_path: "assets/chemistry_lab/lab_001/lab_001.usd"

max_episodes: 50

infer:
  type: "local"
  obs_names: {"camera_1_rgb": 'camera_1_rgb', "camera_2_rgb": 'camera_2_rgb'}

  policy_model_path: "outputs/train/2025.07.29/17.08.44_train_act_image_pick_act/checkpoints/latest.ckpt"
  policy_config_path: "outputs/train/2025.07.29/17.08.44_train_act_image_pick_act/.hydra/config.yaml"
  normalizer_path: "outputs/train/2025.07.29/17.08.44_train_act_image_pick_act/checkpoints/normalize.ckpt"

  host: "101.126.156.90"
  port: 10023
  n_obs_steps: 3
  timeout: 30
  max_retries: 3

  is_test_material: False

task:
  max_steps: 4000
  door_paths:
    - path: "/World/DryingBox_01"
      position_range:
        x: [0.72, 0.77]
        y: [0.0, 0.15]
        z: [0.78, 0.78]
    - path: "/World/MuffleFurnace"
      position_range:
        x: [0.65, 0.70]
        y: [-0.05, 0.010]
        z: [0.78, 0.78]

  obj_paths:
    - path: "/World/beaker2"
      position_range:
        x: [0.19, 0.34]
        y: [0.10, 0.25]
        z: [0.84, 0.84]
    - path: "/World/target_plat"
      position_range:
        x: [0.2, 0.3]
        y: [-0.3, -0.2]
        z: [0.776, 0.776]
  stir_tool_path: "/World/glass_rod"
  stir_tool_mesh_path: "/World/glass_rod/mesh"
  test_tube_rack_path: "/World/test_tube_rack"
  
cameras:
  - prim_path: "/World/Camera1"
    name: "camera_1"
    translation: [-0.7, 1.4, 1.4]
    resolution: [256, 256]
    focal_length: 2
    orientation: [-0.2297, -0.18336, 0.59631, 0.74701]
    image_type: "rgb"

  - prim_path: "/World/Camera2"
    name: "camera_2"
    translation: [-1, -0.1, 3.6]
    resolution: [256, 256]
    focal_length: 4
    orientation: [0.69035, 0.15304, -0.15304, -0.69035]
    image_type: "rgb"

  - prim_path: "/World/Franka/panda_hand/arm_camera"
    name: "camera_3"
    resolution: [256, 256]
    image_type: "rgb"

robot:
  type: "franka"
  position: [-0.4, -0, 0.71]

collector:
  type: "default"
  compression: gzip

hydra:
  run:
    dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}

multi_run:
  run_dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name} 