name: Level3_pick

task_type: "pick"
controller_type: "pick"

mode: "collect"
usd_path: "assets/chemistry_lab/lab_001/lab_001.usd"


max_episodes: 100

infer:
  type: "local"
  obs_names: {"camera_1_rgb": 'camera_1_rgb', "camera_2_rgb": 'camera_2_rgb'}
  policy_model_path: ""
  policy_config_path: ""
  normalizer_path: ""
  host: "127.0.0.1"
  port: 8000
  n_obs_steps: 1
  timeout: 30
  max_retries: 3

  is_test_material: False
  
task:
  max_steps: 1000
  obj_paths:
    - path: "/World/conical_bottle02"
      position_range:
        x: [0.21, 0.36]
        y: [-0.08, 0.08]
        z: [0.82, 0.82]
    - path: "/World/conical_bottle03"
      position_range:
        x: [0.21, 0.36]
        y: [-0.08, 0.08]
        z: [0.82, 0.82]
    - path: "/World/conical_bottle04"
      position_range:
        x: [0.21, 0.36]
        y: [-0.08, 0.08]
        z: [0.82, 0.82]
  material_paths:
    - path: /World/table/surface
      materials:
        - "/World/Looks/Material1_plastic_dark_blue"
        - "/World/Looks/Material2_wood"
        - "/World/Looks/Material3_plastic_dark_green"
        - "/World/Looks/Material4_plastic_light_white"
        - "/World/Looks/Material5_black"
      test_materials:
        - "/World/Looks/Material6_plastic_light_blue"
        - "/World/Looks/Material7_stainless"

cameras:
  - prim_path: "/World/Camera1"
    name: "camera_1"
    translation: [2, 0, 2]
    resolution: [256, 256]
    focal_length: 6
    orientation: [0.61237, 0.35355, 0.35355, 0.61237]
    image_type: "rgb"

  - prim_path: "/World/Camera2"
    name: "camera_2"
    translation: [0.1, 0, 2.5]
    resolution: [256, 256]
    focal_length: 6
    orientation: [0.70711, 0, 0, -0.70711]
    image_type: "rgb"

  - prim_path: "/World/Franka/panda_hand/arm_camera"
    name: "camera_3"
    resolution: [256, 256]
    image_type: "rgb"

robot:
  type: "franka"
  position: [-0.4, -0, 0.71]

collector:
  type: "default"
  compression: gzip

hydra:
  run:
    dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}

multi_run:
  run_dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}
